apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
  namespace: ingress
spec:
  selector:
    app: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-deployment-ingress
  namespace: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Ensures traffic is handled by the NGINX Ingress controller
spec:
  rules:
    - host: erfan.erfan-lab.shop  # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-deployment-service
                port:
                  number: 80