replicaCount: 2

image:
  repository: erfanniks/nginx-custom  # Docker Hub repository
  tag: "1.0"  # Image version tag
  pullPolicy: IfNotPresent

service:
  type: ClusterIP  # Or LoadBalancer if you want external access
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: erfan.erfan-lab.shop  # Replace with your domain
      paths:
        - path: /
          pathType: Prefix

resources: {}  # Specify if you have resource requests/limits for containers

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80